In [1]:
import pandas as pd
import numpy as np
import json 
import csv

In [2]:
ticket_data1 = pd.read_csv("data/Parking_Tags_Data_2018_1.csv")
ticket_data2 = pd.read_csv("data/Parking_Tags_Data_2018_2.csv")
ticket_data3 = pd.read_csv("data/Parking_Tags_Data_2018_3.csv")

In [3]:
concated_pd = pd.concat([ticket_data1, ticket_data2, ticket_data3])
concated_pd.describe()

,date_of_infraction,infraction_code,set_fine_amount,time_of_infraction
count,2.044288e+06,2.044288e+06,2.044288e+06,2.042756e+06
mean,2.018068e+07,8.779510e+01,4.901790e+01,1.146483e+03
std,3.412525e+02,1.353905e+02,4.744234e+01,6.032284e+02
min,2.018010e+07,1.000000e+00,0.000000e+00,0.000000e+00
25%,2.018041e+07,4.000000e+00,3.000000e+01,7.590000e+02
50%,2.018070e+07,9.000000e+00,3.000000e+01,1.158000e+03
75%,2.018100e+07,2.070000e+02,5.000000e+01,1.613000e+03
max,2.018123e+07,4.240000e+02,4.500000e+02,3.458000e+03

In [12]:
parking_violation = concated_pd.loc[(concated_pd['infraction_code'] == 29 ) | (concated_pd['infraction_code'] == 207)]
parking_violation = parking_violation.loc[parking_violation['province'] == 'ON']

In [21]:
parking_violation.head(5)

,tag_number_masked,date_of_infraction,infraction_code,infraction_description,set_fine_amount,time_of_infraction,location1,location2,location3,location4,province
1,***71708,20180101,29,PARK PROHIBITED TIME NO PERMIT,30,2.0,NR,266 DOVERCOURT RD,NaN,NaN,ON
2,***92311,20180101,29,PARK PROHIBITED TIME NO PERMIT,30,2.0,NR,15 FAIRBANK AVE,NaN,NaN,ON
3,***92312,20180101,29,PARK PROHIBITED TIME NO PERMIT,30,2.0,NR,15 FAIRBANK AVE,NaN,NaN,ON
4,***71709,20180101,29,PARK PROHIBITED TIME NO PERMIT,30,3.0,NR,266 DOVERCOURT RD,NaN,NaN,ON
7,***92313,20180101,29,PARK PROHIBITED TIME NO PERMIT,30,3.0,NR,15 FAIRBANK AVE,NaN,NaN,ON

# Top 100 most dangerous parking location

In [61]:
dan_locations = parking_violation['location2'].value_counts()[:100].index.tolist()

In [62]:
from geopy.geocoders import Nominatim
li = []
geolocator = Nominatim(user_agent="specify_your_app_name_here")
for loc in dan_locations:
    try:
        location = geolocator.geocode(loc + " Toronto, Ontario, Canada")
        print(location.latitude, location.longitude)
        li.append([location.latitude, location.longitude])
    except:
        print(loc + " Toronto, Ontario, Canada" + " doesn't return geo-location")

43.629106300000004 -79.47541067335007
43.6591927 -79.3860233
43.665086849999994 -79.37967475694863
43.66733945 -79.3872088302951
43.664706914285716 -79.4654694142857
43.66412355 -79.38161557959802
43.6414865 -79.449486
43.6412811 -79.4515993
43.6650916 -79.4656227
43.6592117 -79.3853392
43.6536408 -79.37780684414469
43.6447036 -79.3918756
43.65353 -79.38637
43.653963 -79.387207
43.6488527 -79.3730035
43.6404401 -79.42457159222741
43.66575 -79.386053
43.7051221 -79.5153282
43.6502266 -79.3691162
43.66585 -79.385535
43.6648306 -79.4655193
43.6544937 -79.3866913
43.660318 -79.373158
43.65694125806451 -79.38206729032258
43.6404961 -79.4513923
43.6502266 -79.3691162
43.6592263 -79.377322403801
43.6593626 -79.3869133
43.63947795 -79.4151685945755
43.643628038461536 -79.40068980769232
43.702995 -79.398633
43.65164 -79.3670758
43.6710622 -79.4294298
43.706533300000004 -79.40338099387839
43.6607675 -79.398261
43.64698945 -79.37472225254237
43.6593626 -79.3869133
43.7623954 -79.4128127572379
43.6581023 -79.3879399
43.650967263157895 -79.3795677368421
43.6492514 -79.3724309
43.64240135 -79.42463363489082
14 MC CAUL ST Toronto, Ontario, Canadadoesn't return geo-location
43.663648 -79.384884
43.6562738 -79.3847663
43.6603276 -79.3461841
43.6542792 -79.3815856
43.6411571 -79.4491262
43.6593626 -79.3869133
43.6439014 -79.3994795
43.658013272727274 -79.37602281818182
43.63858105 -79.4247505222261
43.6503284 -79.39269091959227
43.66532925 -79.37860945381635
43.65120175 -79.35897700996043
43.6390977 -79.4165625
43.6639599 -79.3786768
43.653993 -79.374353
43.6769574 -79.3900603
43.646837149999996 -79.37513086658939
43.649522399999995 -79.38841120000001
43.6191136 -79.4994498
43.66561 -79.387169
43.650861 -79.365395
43.7051221 -79.5153282
43.665761 -79.387565
43.6568668 -79.3497916
43.6591927 -79.3860233
43.6711317 -79.3921498
43.6506636 -79.3602108
43.66037228144322 -79.34618913634765
43.64062130000001 -79.42572169665205
43.6484331 -79.5077093
43.6546639 -79.3842921
43.6609769 -79.4226255
43.6478709 -79.3772414
43.6513744 -79.3953227
43.7053391 -79.3932516
43.6527432 -79.3556738
43.7038773 -79.3755842
43.6420062 -79.4494576
43.640836979999996 -79.45144426
43.6591927 -79.3860233
21 MC CAUL ST Toronto, Ontario, Canadadoesn't return geo-location
43.674862 -79.3904659
43.6417492 -79.450807
43.648831666666666 -79.3987275
43.764730751439394 -79.49568214315104
43.6475888 -79.5142391
43.65378105263158 -79.3889664736842
137 EDWARD ST Toronto, Ontario, Canadadoesn't return geo-location
43.6680735 -79.376018
43.6484558 -79.4523431
22 MC CAUL ST Toronto, Ontario, Canadadoesn't return geo-location
43.66943166666667 -79.382797
43.6554947 -79.3875818
43.6656637 -79.3970837
43.6600955 -79.398582
43.6663562 -79.3429711
43.6707065 -79.391213

In [63]:
dang_parking_geoloc = li

In [64]:
len(dang_parking_geoloc)

96

In [65]:
with open('data/parking-stall-data.json') as f:
  data = json.load(f)

In [66]:
from math import radians, cos, sin, asin, sqrt

def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles
    return c * r

# Put danger property for each parking stall

In [74]:
for park in data['carparks']:
    min_dis = 99999999999.0
    for dan in dang_parking_geoloc:
            distance = haversine(float(park['lat']), float(park['lng']), dan[0], dan[1])
            if distance < min_dis:
                min_dis = distance
    if min_dis < 0.2:
        park['danger'] = 'true'
    else:
        park['danger'] = 'false'

In [77]:
with open('data/parking-stall-data-w-dan.json', 'w') as f:
    json.dump(data, f)